[versions]
commonsLang3 = "3.20.0"
detekt = "2.0.0-alpha.2"
ktlintCustomRules = "0.1.1"
grizzlyHttpServer = "4.0.2"
junit = "4.13.2"
kotest = "6.1.2"
kotlin = "2.3.0"
kotlinxSerialization = "1.10.0"
ktlint = "1.8.0"
kover = "0.9.4"
logback = "1.5.27"
mavenPublishPlugin = "0.36.0"
mockk = "1.14.9"
slf4j = "2.0.17"

[libraries]
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
grizzly-http-server = { module = "org.glassfish.grizzly:grizzly-http-server", version.ref = "grizzlyHttpServer" }
junit = { module = "junit:junit", version.ref = "junit" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
# just here so renovate picks it up
# noinspection UnusedVersionCatalogEntry
ktlint = { module = "com.pinterest.ktlint:ktlint-bom", version.ref = "ktlint" }

# just here so renovate picks it up
# noinspection UnusedVersionCatalogEntry
ktlintCustomRules = { module = "com.eygraber.ktlint.rules:ktlint-rules", version.ref = "ktlintCustomRules" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
abiCompat = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishPlugin" }
